import type { MetadataRoute } from "next";

const BASE = "https://jourdanlabs.com";

export default function sitemap(): MetadataRoute.Sitemap {
  const routes = [
    { url: BASE, priority: 1.0 },
    { url: `${BASE}/cosmic`, priority: 0.9 },
    { url: `${BASE}/alchemist`, priority: 0.9 },
    { url: `${BASE}/alchemist/banking`, priority: 0.86 },
    { url: `${BASE}/alchemist/accounting`, priority: 0.86 },
    { url: `${BASE}/alchemist/cipher`, priority: 0.85 },
    { url: `${BASE}/alchemist/comps`, priority: 0.8 },
    { url: `${BASE}/alchemist/models/credit`, priority: 0.76 },
    { url: `${BASE}/alchemist/models/merger`, priority: 0.76 },
    { url: `${BASE}/alchemist/models/lbo`, priority: 0.76 },
    { url: `${BASE}/alchemist/models/sotp`, priority: 0.76 },
    { url: `${BASE}/alchemist/models/scenarios`, priority: 0.76 },
    { url: `${BASE}/alchemist/models/benchmark`, priority: 0.76 },
    { url: `${BASE}/alchemist/ledgerproof`, priority: 0.84 },
    { url: `${BASE}/alchemist/ledgerproof/recon`, priority: 0.76 },
    { url: `${BASE}/alchemist/ledgerproof/journal`, priority: 0.76 },
    { url: `${BASE}/alchemist/ledgerproof/flux`, priority: 0.76 },
    { url: `${BASE}/alchemist/ledgerproof/binder`, priority: 0.76 },
    { url: `${BASE}/alchemist/ledgerproof/policy`, priority: 0.76 },
    { url: `${BASE}/alchemist/ledgerproof/control`, priority: 0.76 },
    { url: `${BASE}/omnis`, priority: 0.88 },
    { url: `${BASE}/omnis/cadmus`, priority: 0.82 },
    { url: `${BASE}/omnis/vantage`, priority: 0.82 },
    { url: `${BASE}/omnis/prospector`, priority: 0.82 },
    { url: `${BASE}/omnis/luna`, priority: 0.82 },
    { url: `${BASE}/divisions`, priority: 0.9 },
    { url: `${BASE}/divisions/atlas`, priority: 0.8 },
    { url: `${BASE}/divisions/bacchus`, priority: 0.8 },
    { url: `${BASE}/divisions/helix`, priority: 0.8 },
    { url: `${BASE}/divisions/heimdall`, priority: 0.8 },
    { url: `${BASE}/crucible`, priority: 0.9 },
    { url: `${BASE}/crucible/vantage`, priority: 0.85 },
    { url: `${BASE}/crucible/benchmarks`, priority: 0.85 },
    { url: `${BASE}/crucible/benchmarks/signal`, priority: 0.8 },
    { url: `${BASE}/crucible/benchmarks/citadel`, priority: 0.8 },
    { url: `${BASE}/crucible/benchmarks/sentinel`, priority: 0.8 },
    { url: `${BASE}/crucible/benchmarks/oracle`, priority: 0.8 },
    { url: `${BASE}/crucible/benchmarks/lens`, priority: 0.8 },
    { url: `${BASE}/crucible/benchmarks/compass`, priority: 0.8 },
    { url: `${BASE}/crucible/methodology`, priority: 0.85 },
    { url: `${BASE}/crucible/reproducibility`, priority: 0.8 },
    { url: `${BASE}/crucible/raven`, priority: 0.5 },
    { url: `${BASE}/applications`, priority: 0.75 },
    { url: `${BASE}/northstar`, priority: 0.75 },
    { url: `${BASE}/contact`, priority: 0.6 },
  ];

  return routes.map(({ url, priority }) => ({
    url,
    lastModified: new Date("2026-05-26"),
    changeFrequency: "monthly" as const,
    priority,
  }));
}
