// 6D Workbench — markdown export (per phase + full bundle).
// Pure string assembly from the manifest; the export is as deterministic as
// the run it describes.

import type { ArtifactElement, PhaseArtifact, RunManifest } from "./types";

export const KIND_TITLES: Record<string, string> = {
  objective: "Objective",
  problem_statement: "Problem / current state",
  in_scope: "In scope",
  out_of_scope: "Out of scope",
  assumption: "Assumptions",
  story: "Stories",
  acceptance_criterion: "Acceptance criteria",
  success_metric: "Success metrics",
  design_direction: "Design direction",
  adr: "Decision records",
  ux_consideration: "UX considerations",
  state: "States",
  epic: "Epic",
  dependency_graph: "Dependencies",
  implementation_plan: "Implementation plans",
  dev_prompt: "Dev prompts (emitted by CADMUS)",
  edge_case: "Edge cases",
  contract: "Contracts",
  handoff: "Handoff",
  test_scenario: "Test scenarios",
  coverage_map: "Coverage",
  scaffold: "Scaffolding",
  release_notes: "Release notes",
  runbook_input: "Runbook inputs",
  monitoring_question: "Monitoring questions",
};

const renderElement = (e: ArtifactElement): string[] => {
  const L: string[] = [];
  if (e.title) L.push(`**${e.title}**`);
  const lang = e.fields?.language as string | undefined;
  if (lang) {
    L.push("```" + lang, e.body, "```");
  } else {
    L.push(e.body);
  }
  const chips: string[] = [];
  if (e.fields?.estimate) chips.push(`estimate: ${e.fields.estimate}`);
  if (e.fields?.labels) chips.push(`labels: ${(e.fields.labels as string[]).join(", ")}`);
  if (Array.isArray(e.fields?.dependsOn) && (e.fields.dependsOn as string[]).length)
    chips.push(`depends on: ${(e.fields.dependsOn as string[]).join(", ")}`);
  if (e.fields?.type) chips.push(`type: ${e.fields.type}`);
  if (chips.length) L.push(`*${chips.join(" · ")}*`);
  L.push(`<sub>↳ trace: ${e.sourceRefs.join(", ")} · id: ${e.id}</sub>`);
  L.push("");
  return L;
};

export function phaseMarkdown(art: PhaseArtifact): string {
  const L: string[] = [];
  L.push(`## ${art.n} · ${art.name} (${art.role}) — ${art.deliverable}`);
  L.push("");
  const kindsInOrder: string[] = [];
  for (const e of art.elements) if (!kindsInOrder.includes(e.kind)) kindsInOrder.push(e.kind);
  for (const kind of kindsInOrder) {
    L.push(`### ${KIND_TITLES[kind] ?? kind}`);
    L.push("");
    for (const e of art.elements.filter((x) => x.kind === kind)) L.push(...renderElement(e));
  }
  if (art.openQuestions.length) {
    L.push(`### Open questions — honest gaps, not guesses`);
    L.push("");
    for (const q of art.openQuestions) {
      L.push(`- ${q.blocking ? "**[BLOCKING]** " : ""}${q.question} _(${q.id})_`);
    }
    L.push("");
  }
  return L.join("\n");
}

export function bundleMarkdown(m: RunManifest): string {
  const L: string[] = [];
  L.push(`# 6D Workbench — ${m.intent.title}`);
  L.push("");
  L.push(`> Generated by the ${m.generatedBy}.`);
  L.push(`> **Receipt (SHA-256):** \`${m.receipt}\``);
  L.push(`> Same intent in, same artifacts out, same hash — re-run it and check.`);
  L.push(`> Draft accelerators: every artifact is reviewed by its accountable owner.`);
  L.push("");
  L.push(`## Feature intent`);
  L.push("");
  L.push(`**${m.intent.title}**`);
  L.push("");
  L.push(m.intent.context);
  L.push("");
  if (m.intent.goals.length) {
    L.push(`**Goals:**`);
    m.intent.goals.forEach((g) => L.push(`- ${g}`));
    L.push("");
  }
  if (m.intent.constraints.length) {
    L.push(`**Constraints:**`);
    m.intent.constraints.forEach((c) => L.push(`- ${c}`));
    L.push("");
  }
  for (const art of m.artifacts) {
    L.push(phaseMarkdown(art));
    L.push("");
  }
  L.push("---");
  L.push(
    `*Deterministic · keyless · zero egress. Every element above carries a trace back to the intent (\`↳ trace\`). Open questions are honest gaps — the engine refuses to invent what it was not given.*`,
  );
  return L.join("\n");
}
